language: java
jdk:
  - oraclejdk8

script:
 - # bulding libPlg
 - cd libPlg
 - ant
 - cd ..
 - # building plg-cli
 - #cp libPlg/dist/libPlg.jar plg-cli/lib/libPlg/
 - #cd plg-cli
 - #ant LogGenerator